

--SELECT * FROM VADVERTENCIA --> SOMAR QUANTAS ADVERTENCIAS CADA FUNCIONÁRIO POSSUI E COLOCAR NA COLUNA.

DECLARE @DATA_INI DATETIME
,@DATA_FIM DATETIME
,@COLIGADA INT


SET @DATA_INI = CAST('20200109' AS DATETIME)
SET @DATA_FIM = CAST('20200309' AS DATETIME)
SET @COLIGADA = 1


SELECT CHAPA,NOME,SECAO,FUNCAO,SUM(ATESTADO_DIAS) AS ATESTADO_DIAS,SUM(ATESTADOS) AS ATESTADOS,SUM(FALTA) AS FALTA,SUM(SUSPENSAO_DIAS) AS SUSPENSAO_DIAS,SUM(SUSPENSOES) AS SUSPENSOES

FROM (
SELECT 
CHAPA
,NOME
,SECAO
,FUNCAO
,(CASE WHEN DESCRICAO = 'ATESTADO' THEN [QUANT DIAS] ELSE '' END ) AS ATESTADO_DIAS
,(CASE WHEN DESCRICAO = 'ATESTADO' THEN 1 ELSE 0 END ) AS ATESTADOS
,(CASE WHEN DESCRICAO = 'FALTA' THEN [QUANT DIAS] ELSE '' END) AS FALTA
,(CASE WHEN DESCRICAO = 'SUSPENSAO' THEN [QUANT DIAS] ELSE '' END) AS SUSPENSAO_DIAS
,(CASE WHEN DESCRICAO = 'SUSPENSAO' THEN 1 ELSE 0 END) AS SUSPENSOES

FROM (
SELECT PFUNC.CHAPA 
,PFUNC.NOME
,PSECAO.DESCRICAO AS SECAO
,PFUNCAO.NOME AS FUNCAO
,'ATESTADO' AS DESCRICAO
,VATESTADO.DTINICIO AS DATA_INI
,VATESTADO.DTFINAL AS DATA_FIM
,(CASE WHEN DATEDIFF(DAY, VATESTADO.DTINICIO, VATESTADO.DTFINAL) <= 0
THEN (DATEDIFF(DAY, VATESTADO.DTINICIO, VATESTADO.DTFINAL) + 1)
ELSE (DATEDIFF(DAY, VATESTADO.DTINICIO, VATESTADO.DTFINAL) + 1) END) AS [QUANT DIAS]
FROM VCHAPAATESTADO
LEFT OUTER JOIN PFUNC(NOLOCK) ON (((VCHAPAATESTADO.CHAPA = PFUNC.CHAPA) AND (VCHAPAATESTADO.CODCOLIGADA = PFUNC.CODCOLIGADA)))
LEFT OUTER JOIN VATESTADO(NOLOCK) ON (((VCHAPAATESTADO.CODPESSOA = VATESTADO.CODPESSOA) AND (VCHAPAATESTADO.CODCOLIGADA = VATESTADO.CODCOLIGADA)
AND (VCHAPAATESTADO.DTINICIO = VATESTADO.DTINICIO)))
LEFT OUTER JOIN VTIPOATESTADO(NOLOCK) ON (VATESTADO.CODTPATESTADO = VTIPOATESTADO.CODTPATESTADO)
LEFT OUTER JOIN VCID(NOLOCK) ON (VATESTADO.CID = VCID.CID)
LEFT OUTER JOIN PFUNCAO(NOLOCK) ON (((VCHAPAATESTADO.CODCOLIGADA = PFUNCAO.CODCOLIGADA) AND (PFUNC.CODFUNCAO = PFUNCAO.CODIGO)))
LEFT OUTER JOIN PSECAO(NOLOCK) ON (((VCHAPAATESTADO.CODCOLIGADA = PSECAO.CODCOLIGADA) AND (PFUNC.CODSECAO = PSECAO.CODIGO)))
LEFT OUTER JOIN VPROFISSIONALSAUDE(NOLOCK) ON (VATESTADO.CODMEDICO = VPROFISSIONALSAUDE.CODIGO)
WHERE VATESTADO.CODCOLIGADA = @COLIGADA AND (VATESTADO.DTINICIO BETWEEN @DATA_INI AND @DATA_FIM OR VATESTADO.DTFINAL BETWEEN @DATA_INI AND @DATA_FIM)

UNION ALL  

Select   
Ocorrencia.CHAPA as CHAPA,
PFUNC.NOME as NOME,
PSECAO.DESCRICAO AS SECAO,
PFUNCAO.NOME AS FUNCAO,
'FALTA' AS DESCRICAO,
Ocorrencia.DATA AS DATA_INI, '' AS DATA_FIM, 1 QUANT
from
(

Select
AJUSTFUN.CODCOLIGADA,
AJUSTFUN.CHAPA,
AJUSTFUN.DATA,
AJUSTFUN.ATITUDE,
CAST(CONVERT(NUMERIC,SUM(AJUSTFUN.NUMHORAS))/60 AS DECIMAL(10,2)) as HRS_FALTAS
from AJUSTFUN as AJUSTFUN (NOLOCK)
Where 1 = 1 AND AJUSTFUN.CODCOLIGADA = @COLIGADA AND AJUSTFUN.DATA  BETWEEN @DATA_INI AND @DATA_FIM
AND AJUSTFUN.TIPOOCORRENCIA = 'F' AND AJUSTFUN.ATITUDE <> '1'
GROUP BY AJUSTFUN.CODCOLIGADA, AJUSTFUN.CHAPA, AJUSTFUN.DATA, AJUSTFUN.TIPOOCORRENCIA, AJUSTFUN.ATITUDE

) Ocorrencia

Inner Join PFUNC as PFUNC (nolock) ON PFUNC.CODCOLIGADA = Ocorrencia.CODCOLIGADA AND PFUNC.CHAPA = Ocorrencia.CHAPA
Inner Join PSECAO as PSECAO (nolock) ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA  AND PSECAO.CODIGO = PFUNC.CODSECAO
Inner Join PFUNCAO as PFUNCAO (nolock) ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
Where 1 = 1 AND CAST(Ocorrencia.CODCOLIGADA AS VARCHAR)+Ocorrencia.CHAPA+convert(varchar(8),Ocorrencia.DATA,112)
NOT IN (SELECT CAST(AAFHTFUN.CODCOLIGADA AS VARCHAR)+AAFHTFUN.CHAPA+convert(varchar(8),AAFHTFUN.DATA,112) as DATA
FROM AAFHTFUN
INNER JOIN PFUNC ON PFUNC.CHAPA = AAFHTFUN.CHAPA AND PFUNC.CODCOLIGADA = AAFHTFUN.CODCOLIGADA
AND AAFHTFUN.DATA BETWEEN @DATA_INI AND @DATA_FIM AND AAFHTFUN.CODCOLIGADA = @COLIGADA
LEFT JOIN (

SELECT SUSP.CHAPA, SUSP.CODCOLIGADA, cast(SUSP.DATAINICIO as datetime) AS DATA_INI, cast(SUSP.DATAFIM as datetime) AS DATA_FIM
FROM ASUSPENSAO SUSP WITH (NOLOCK)
INNER JOIN PFUNC FUNC WITH (NOLOCK) ON SUSP.CHAPA = FUNC.CHAPA AND (DATAINICIO BETWEEN @DATA_INI AND @DATA_FIM
OR DATAFIM BETWEEN @DATA_INI AND @DATA_FIM) AND FUNC.CODCOLIGADA = SUSP.CODCOLIGADA
WHERE FUNC.CODCOLIGADA = @COLIGADA ) TABELA99  

ON TABELA99.CHAPA = AAFHTFUN.CHAPA AND TABELA99.CODCOLIGADA=AAFHTFUN.CODCOLIGADA AND AAFHTFUN.DATA BETWEEN TABELA99.DATA_INI AND TABELA99.DATA_FIM

WHERE AAFHTFUN.DATA BETWEEN @DATA_INI AND @DATA_FIM AND PFUNC.CHAPA = AAFHTFUN.CHAPA AND AAFHTFUN.CODCOLIGADA = @COLIGADA
AND PFUNC.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND CAST(CONVERT(NUMERIC, AAFHTFUN.FALTA) / 60 AS DECIMAL(10, 2)) <> 0
AND AAFHTFUN.DATA BETWEEN TABELA99.DATA_INI AND TABELA99.DATA_FIM)

UNION ALL -- 

SELECT SUSP.CHAPA
,FUNC.NOME
,SECAO.DESCRICAO AS SECAO
,FUNCAO.NOME AS FUNCAO
,'SUSPENSÃO' AS DESCRICAO
,SUSP.DATAINICIO AS DATA_INI
,SUSP.DATAFIM AS DATA_FIM
,(CASE WHEN DATEDIFF(DAY, SUSP.DATAINICIO, SUSP.DATAFIM) <= 0 THEN (DATEDIFF(DAY, SUSP.DATAINICIO, SUSP.DATAFIM) + 1) ELSE (DATEDIFF(DAY, SUSP.DATAINICIO, SUSP.DATAFIM) + 1) END) AS [QUANT DIAS]
FROM ASUSPENSAO SUSP WITH (NOLOCK)
INNER JOIN PFUNC FUNC WITH (NOLOCK) ON SUSP.CHAPA = FUNC.CHAPA AND (DATAINICIO BETWEEN @DATA_INI AND @DATA_FIM OR DATAFIM BETWEEN @DATA_INI
AND @DATA_FIM) AND FUNC.CODCOLIGADA = SUSP.CODCOLIGADA
INNER JOIN PSECAO SECAO WITH (NOLOCK) ON SECAO.CODIGO = FUNC.CODSECAO AND FUNC.CODCOLIGADA = SECAO.CODCOLIGADA
INNER JOIN PFUNCAO FUNCAO WITH (NOLOCK) ON FUNC.CODCOLIGADA = FUNCAO.CODCOLIGADA AND FUNC.CODFUNCAO = FUNCAO.CODIGO
WHERE FUNC.CODCOLIGADA = @COLIGADA
) TAB
) TABELA33
GROUP BY
CHAPA,NOME,SECAO,FUNCAO
ORDER BY CHAPA, NOME

