SELECT CQ.R_E_C_N_O_ AS PREREQRECNO,CP.R_E_C_N_O_ SOLICITRECNO, CP_FILIAL AS EMPRESA, CP_PRODUTO CODIGO, CP_ITEM SEQUENCIA, BM_DESC GRUPO, B1_COD CODIGOPRODUTO, CP_LOCAL ARMAZEM, 
B1_DESC DESCRICAODOPRODUTO, DATEPART(YYYY,CP_EMISSAO) AS ANO, CASE WHEN DATEPART(MONTH, CP_EMISSAO) = 1 THEN '01 - JANEIRO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 2 THEN '02 - FEVEREIRO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 3 THEN '03 - MARÇO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 4 THEN '04 - ABRIL'
WHEN DATEPART(MONTH, CP_EMISSAO) = 5 THEN '05 - MAIO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 6 THEN '06 - JUNHO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 7 THEN '07 - JULHO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 8 THEN '08 - AGOSTO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 9 THEN '09 - SETEMBRO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 10 THEN '10 - OUTUBRO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 11 THEN '01 - NOVEMBRO'
WHEN DATEPART(MONTH, CP_EMISSAO) = 12 THEN '01 - DEZEMBRO' END AS MES
, CP_EMISSAO AS EMISSAO, B1_UM AS UNIDADE, CP_QUANT AS QUANTSOLICIT,CQ_QUANT AS QUANTPREREQUISIT, CP_QUJE AS QUANTJAATENDIDA
,CP_VUNIT AS VALORUNIT, 'ENCERRADO', CONVERT(DATE, CQ_DATPRF, 103) AS DTPREREQUISICAO, 
DATEPART(YYYY,CQ_DATPRF) AS ANOPREREQUISIT, CASE WHEN DATEPART(MONTH, CP_EMISSAO) = 1 THEN '01 - JANEIRO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 2 THEN '02 - FEVEREIRO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 3 THEN '03 - MARÇO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 4 THEN '04 - ABRIL'
WHEN DATEPART(MONTH, CQ_DATPRF) = 5 THEN '05 - MAIO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 6 THEN '06 - JUNHO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 7 THEN '07 - JULHO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 8 THEN '08 - AGOSTO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 9 THEN '09 - SETEMBRO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 10 THEN '10 - OUTUBRO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 11 THEN '01 - NOVEMBRO'
WHEN DATEPART(MONTH, CQ_DATPRF) = 12 THEN '01 - DEZEMBRO' END AS MESPREREQUISIT, CP_CC AS CC, CTT_DESC01 AS DESCRICAOCC, CP_SOLICIT AS SOLICITANTE
FROM SCP010 CP 
INNER JOIN SCQ010 CQ ON CP_NUM=CQ_NUM AND CP_FILIAL=CQ_FILIAL AND CQ_PRODUTO =CP_PRODUTO
INNER JOIN SB1010 B1 ON B1_COD=CP_PRODUTO AND B1_FILIAL='0101'
INNER JOIN SBM010 BM ON B1_GRUPO=BM_GRUPO AND BM_FILIAL='0101'
INNER JOIN CTT010 CT ON CTT_CUSTO=CP_CC AND CTT_FILIAL=CP_FILIAL
WHERE CP_EMISSAO>'20210101' AND CP_PRODUTO='E00B00124' AND CP_STATUS='E'



