BEGIN TRANSACTION; 
UPDATE  SA1010  SET  A1_EMCERT = 'laboratorio@azevedooleos.com.br; compras2@azevedooleos.com.br',A1_EMFAT = 'nfe@azevedooleos.com.br; financeiro@azevedooleos.com.br; compras2@azevedooleos.com.br'  WHERE A1_COD = '002955'
UPDATE  SA1010  SET  A1_EMCERT = 'financeiroaparagao@gmail.com; guyllennearagao@gmail.com; italoholanda73@hotmail.com',A1_EMFAT = 'financeiroaparagao@gmail.com; guyllennearagao@gmail.com; italoholanda73@hotmail.com'  WHERE A1_COD = '002971'
UPDATE  SA1010  SET  A1_EMCERT = 'fabio.carrera@petruz.com;savio.cavalcanti@petruz.com;compras04@petruz.com;compras06@petruz.com' WHERE A1_COD = '000643'
UPDATE  SA1010  SET  A1_EMFAT = 'fabio.carrera@petruz.com;savio.cavalcanti@petruz.com;compras04@petruz.com;compras06@petruz.com;compras05@petruz.com' WHERE A1_COD = '000643'
UPDATE  SA1010  SET  A1_EMCERT = 'maria.aline@brf.com.br; jhenifer.bonfim@brf.com.br; daniel.araujo@brf.com.br'  WHERE A1_COD = '002060'
UPDATE  SA1010  SET  A1_EMCERT = 'maria.aline@brf.com.br; jhenifer.bonfim@brf.com.br; daniel.araujo@brf.com.br'  WHERE A1_COD = '002648'
UPDATE  SA1010  SET  A1_EMCERT = 'maria.aline@brf.com.br; jhenifer.bonfim@brf.com.br; daniel.araujo@brf.com.br'  WHERE A1_COD = '002391'
UPDATE  SA1010  SET  A1_EMCERT = 'maria.aline@brf.com.br; jhenifer.bonfim@brf.com.br; daniel.araujo@brf.com.br'  WHERE A1_COD = '002471'
UPDATE  SA1010  SET  A1_EMCERT = 'sergio.ricardo@dunorte.com; marlucia@cione.com.br; alexandre.carlos@dunorte.com',A1_EMFAT = 'sergio.ricardo@dunorte.com; marlucia@cione.com.br; alexandre.carlos@dunorte.com'  WHERE A1_COD = '002812'
UPDATE  SA1010  SET  A1_EMCERT = 'eduardo.goncalves@clariant.com;etoni.brito@clariant.com;marcio.flausino@clariant.com;geovane.lima@clariant.com',A1_EMFAT = 'eduardo.goncalves@clariant.com;etoni.brito@clariant.com;marcio.flausino@clariant.com;geovane.lima@clariant.com'  WHERE A1_COD = '001916'
UPDATE  SA1010  SET  A1_EMCERT = 'eduardo.goncalves@clariant.com; marcio.flausino@clariant.com; mariana.kumagai@clariant.com',A1_EMFAT = 'eduardo.goncalves@clariant.com; marcio.flausino@clariant.com; mariana.kumagai@clariant.com'  WHERE A1_COD = '003034'
UPDATE  SA1010  SET  A1_EMFAT = 'comprasd@doremus.com.br; financeiro@doremus.com.br; ff@doremus.com.br 'WHERE A1_COD = '000605'          
UPDATE  SA1010  SET  A1_EMCERT = 'maria.aline@brf.com.br;jhenifer.bonfim@brf.com.br;daniel.araujo@brf.com.br'  WHERE A1_COD = '122085'
UPDATE  SA1010  SET  A1_EMFAT = 'evandro.maia@dovac.com.br; margarethe.bertti@dovac.com.br; sandro.tuneli@dovac.com.br'  WHERE A1_COD = '000988'          
UPDATE  SA1010  SET  A1_EMCERT = 'charlesbarreto@jmonte.com.br; paulo.durafix@jmonte.com.br; nilze.durafix@jmonte.com.br',A1_EMFAT = 'charlesbarreto@jmonte.com.br; paulo.durafix@jmonte.com.br; nilze.durafix@jmonte.com.br   'WHERE A1_COD = '002064'
UPDATE  SA1010  SET  A1_EMCERT = 'compras@ecofresh.com.br; nfe@ecofresh.com.br; financeiro@ecofresh.com.br',A1_EMFAT = 'compras@ecofresh.com.br; nfe@ecofresh.com.br; financeiro@ecofresh.com.br;'  WHERE A1_COD = '001941'
UPDATE  SA1010  SET  A1_EMCERT = 'financeiro@tintascoresdobrasil.com.br; contasapagar@tintascoresdobrasil.com.br; compras@tintascoresdobrasil.com.br',A1_EMFAT = 'financeiro@tintascoresdobrasil.com.br; contasapagar@tintascoresdobrasil.com.br; compras@tintascoresdobrasil.com.br'  WHERE A1_COD = '122074'
UPDATE  SA1010  SET  A1_EMCERT = 'agendamento@harald.com.br; laboratoriocq@harald.com.br; patricia.limeira@harald.com.br'  WHERE A1_COD = '003021'
UPDATE  SA1010  SET  A1_EMCERT = 'agendamento@harald.com.br; laboratoriocq@harald.com.br; patricia.limeira@harald.com.br'  WHERE A1_COD = '000426'
UPDATE  SA1010  SET  A1_EMCERT = 'zelena.faturamento@imdepa.com.br; glaciane.freitas@imdepa.com.br; faturamento.spa@imdepa.com.br',A1_EMFAT = 'zelena.faturamento@imdepa.com.br; glaciane.freitas@imdepa.com.br; faturamento.spa@imdepa.com.br'  WHERE A1_COD = '002938'
UPDATE  SA1010  SET  A1_EMCERT = 'jenniferrodrigues.espro@natura.net; sabrinasanches@natura.net; nataliagagini@natura.net; brunaandrade@natura.net',A1_EMFAT = 'jenniferrodrigues.espro@natura.net; sabrinasanches@natura.net; nataliagagini@natura.net; brunaandrade@natura.net'  WHERE A1_COD = '002078'
UPDATE  SA1010  SET  A1_EMCERT = 'recebimento@marvi.com.br; recebimento2@marvi.com.br; controle4.qualidade@marvi.com.br'  WHERE A1_COD = '000188'
UPDATE  SA1010  SET  A1_EMCERT = 'rafaelduransbel@supermassa.com.br; danielqueirozbel@supermassa.com.br',A1_EMFAT = 'rafaelduransbel@supermassa.com.br; danielqueirozbel@supermassa.com.br   'WHERE A1_COD = '002362'
UPDATE  SA1010  SET  A1_EMCERT = 'laboratorio@indutil.com.br; anderson.moraes@indutil.com.br; almoxarifado@indutil.com.br',A1_EMFAT = 'nfe@indutil.com.br; financeiro5@eritram.com.br; financeiro6@eritram.com.br'  WHERE A1_COD = '002310'
UPDATE  SA1010  SET  A1_EMFAT = 'rosangela@isis.com.br; ronaldo@isis.com.br; camila@isis.com.br'  WHERE A1_COD = '000466'          
UPDATE  SA1010  SET  A1_EMCERT = 'zelena.faturamento@imdepa.com.br; glaciane.freitas@imdepa.com.br; faturamento.spa@imdepa.com.br',A1_EMFAT = 'zelena.faturamento@imdepa.com.br; glaciane.freitas@imdepa.com.br; faturamento.spa@imdepa.com.br'  WHERE A1_COD = '000347'
UPDATE  SA1010  SET  A1_EMCERT = 'osvaldo.luz@kerry.com; materia.primacps@kerry.com; elisabete.santos@kerry.com; gabriella.silva@kerry.com; efrain.lima@kerry.com; hosana.souza@kerry.com'  WHERE A1_COD = '002147'
UPDATE  SA1010  SET  A1_EMCERT = 'osvaldo.luz@kerry.com; materia.primacps@kerry.com; elisabete.santos@kerry.com; gabriella.silva@kerry.com; efrain.lima@kerry.com; hosana.souza@kerry.com'  WHERE A1_COD = '000769'
UPDATE  SA1010  SET  A1_EMCERT = 'financeiro@marborges.com.br; almoxarifado@marborges.com.br; compras@marborges.com.br',A1_EMFAT = 'financeiro@marborges.com.br; almoxarifado@marborges.com.br; compras@marborges.com.br'  WHERE A1_COD = '002644'
UPDATE  SA1010  SET  A1_EMCERT = 'sineide.vieira@nouryon.com; leticia.ferraresso@nouryon.com; tayara.vieira@nouryon.com'  WHERE A1_COD = '002873'
UPDATE  SA1010  SET  A1_EMCERT = 'zelena.faturamento@imdepa.com.br; glaciane.freitas@imdepa.com.br; faturamento.spa@imdepa.com.br',A1_EMFAT = 'zelena.faturamento@imdepa.com.br; glaciane.freitas@imdepa.com.br; faturamento.spa@imdepa.com.br'  WHERE A1_COD = '000910'
UPDATE  SA1010  SET  A1_EMCERT = 'compras@ponzan.com.br; cq.ponzan@ponzan.com.br; pd.ponzan@ponzan.com.br',A1_EMFAT = 'compras@ponzan.com.br; escritafiscal@ponzan.com.br; escritafiscal1@ponzan.com.br'  WHERE A1_COD = '122035'
UPDATE  SA1010  SET  A1_EMCERT = 'fiscal@positivebrands.com.br; ferreira@amendoasdobrasil.com.br; brito@amendoasdobrasil.com.br',A1_EMFAT = 'fiscal@positivebrands.com.br; ferreira@amendoasdobrasil.com.br; brito@amendoasdobrasil.com.br'  WHERE A1_COD = '122009'
UPDATE  SA1010  SET  A1_EMCERT = 'financeiro@tintascoresdobrasil.com.br; contasapagar@tintascoresdobrasil.com.br; compras@tintascoresdobrasil.com.br',A1_EMFAT = 'financeiro@tintascoresdobrasil.com.br; contasapagar@tintascoresdobrasil.com.br; compras@tintascoresdobrasil.com.br'  WHERE A1_COD = '002788'
UPDATE  SA1010  SET  A1_EMCERT = 'luana.artundo@unilever.com; viviane.L.Silva@unilever.com; damares.Silva@unilever.com',A1_EMFAT = 'luana.artundo@unilever.com; viviane.L.Silva@unilever.com; damares.Silva@unilever.com'  WHERE A1_COD = '002364'
UPDATE  SA1010  SET  A1_EMCERT = 'weliton.cunha@dunorte.com; gustavo.sampaio@dunorte.com.br; compras@dunorte.com',A1_EMFAT = 'weliton.cunha@dunorte.com; gustavo.sampaio@dunorte.com.br; compras@dunorte.com'  WHERE A1_COD = '001317'
UPDATE  SA1010  SET  A1_EMCERT = 'icaro.ribeiro@vedacit.com.br; carlos.rocha@vedacit.com.br; aldo.queiroz@vedacit.com.br',A1_EMFAT = 'icaro.ribeiro@vedacit.com.br; carlos.rocha@vedacit.com.br; aldo.queiroz@vedacit.com.br'  WHERE A1_COD = '000143'
COMMIT; 

SELECT A1_EMCERT,A1_EMFAT FROM SA1010 WHERE A1_COD = '002147'

