SELECT * FROM SEA010


SELECT EA_BOMCLI,EA_LOCPDF,EA_ENVIADO, EA_CART, R_E_C_N_O_ -- Consulta Filtrando por Cliente 
FROM SEA010
WHERE D_E_L_E_T_ = ' '
AND EA_LOCPDF  <>''
AND EA_ENVIADO = '' 
AND EA_CART = 'R'

EA_FILIAL

SELECT EA_LOCPDF, EA.R_E_C_N_O_
FROM SEA010 EA
INNER JOIN SE1010 E1
ON EA.EA_FILIAL = E1.E1_FILIAL
AND EA.EA_NUM = E1.E1_NUM 
AND EA.EA_PARCELA = E1.E1_PARCELA 
AND EA.EA_NUMBOR = E1.E1_NUMBOR  
AND E1.D_E_L_E_T_ = ' '
WHERE EA.D_E_L_E_T_ = ' ' 
AND EA.EA_LOCPDF  <> ''  
AND EA.EA_ENVIADO = ''
AND EA.EA_BOMCLI = E1.E1_CLIENTE	
AND EA.EA_CART = 'R'